# fly.toml app configuration file generated for job-hunt on 2025-04-08T23:58:03+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-hunt'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
