# fly.toml app configuration file generated for job-hunt-strapi-backend on 2025-04-08T22:54:32+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-hunt-strapi-backend'
primary_region = 'bom'

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
